<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DockDX</AssemblyName>
    <RootNamespace>DockDX</RootNamespace>
    <ApplicationIcon>..\assets\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <StartupObject>DockDX.Program</StartupObject>
    <Version>1.0.0</Version>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <NoWarn>WFAC010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\scripts\media.ps1" LogicalName="media.ps1" />
    <Resource Include="..\assets\icon.png" Link="icon.png" />
  </ItemGroup>

</Project>
